making scripts more readable

diff --git a/bin/extract b/bin/extract
--- a/bin/extract
+++ b/bin/extract
@@ -1,41 +1,28 @@
 #!/bin/env sh
 
-if [ $# -eq 0 ]; then
-    echo "Usage: extract TARGET [DESTINATION_DIR]"
-    exit 1
-fi
+[ $# -eq 0 ] && echo "Usage: extract TARGET [DESTINATION_DIR]" && exit 1
 
 TARGET="$1"
 DESTINATION_DIR="$2"
 
-if [ -z "$DESTINATION_DIR" ]; then
-    DESTINATION_DIR="$PWD"
-fi
-
-if [ ! -d "$DESTINATION_DIR" ]; then
-    echo "Error: Destination directory '$DESTINATION_DIR' does not exist."
-    exit 1
-fi
-
-if [ ! -f "$TARGET" ]; then
-    echo "Error: '$TARGET' is not a valid file."
-    exit 1
-fi
+[ -z "$DESTINATION_DIR" ] && DESTINATION_DIR="$PWD"
+[ ! -d "$DESTINATION_DIR" ] && echo "Error: '$DESTINATION_DIR' does not exist." && exit 1
+[ ! -f "$TARGET" ] && echo "Error: '$TARGET' is not a valid file." && exit 1
 
 case "$TARGET" in
     *.tar.bz2)    tar xjf "$TARGET" -C "$DESTINATION_DIR" ;;
     *.tar.gz)     tar xzf "$TARGET" -C "$DESTINATION_DIR" ;;
-    *.bz2)        bunzip2 "$TARGET" && mv "${TARGET%.*}" "$DESTINATION_DIR" ;; # Move after extraction
+    *.bz2)        bunzip2 "$TARGET" && mv "${TARGET%.*}" "$DESTINATION_DIR" ;;
     *.rar)        unrar x "$TARGET" "$DESTINATION_DIR" ;;
-    *.gz)         gunzip "$TARGET" && mv "${TARGET%.*}" "$DESTINATION_DIR" ;; # Move after extraction
+    *.gz)         gunzip "$TARGET" && mv "${TARGET%.*}" "$DESTINATION_DIR" ;;
     *.tar)        tar xf "$TARGET" -C "$DESTINATION_DIR" ;;
     *.tbz2)       tar xjf "$TARGET" -C "$DESTINATION_DIR" ;;
     *.tgz)        tar xzf "$TARGET" -C "$DESTINATION_DIR" ;;
     *.zip)        unzip "$TARGET" -d "$DESTINATION_DIR" ;;
-    *.Z)          uncompress "$TARGET" && mv "${TARGET%.*}" "$DESTINATION_DIR" ;; # Move after extraction
-    *.7z)         7za e -o"$DESTINATION_DIR" "$TARGET" ;; # Changed to extract to directory
-    *.deb)        ar x "$TARGET" && mv * "$DESTINATION_DIR" ;; # Extract and move all extracted files. Be careful with this!
-    *.tar.xz)    tar xf "$TARGET" -C "$DESTINATION_DIR" ;;
-    *.tar.zst)   unzstd "$TARGET" && mv "${TARGET%.*}" "$DESTINATION_DIR" ;; # Move after extraction
-    *)           echo "'$TARGET' cannot be extracted" ;;
+    *.Z)          uncompress "$TARGET" && mv "${TARGET%.*}" "$DESTINATION_DIR" ;;
+    *.7z)         7za e -o"$DESTINATION_DIR" "$TARGET" ;;
+    *.deb)        ar x "$TARGET" && mv * "$DESTINATION_DIR" ;;
+    *.tar.xz)     tar xf "$TARGET" -C "$DESTINATION_DIR" ;;
+    *.tar.zst)    unzstd "$TARGET" && mv "${TARGET%.*}" "$DESTINATION_DIR" ;;
+    *)            echo "'$TARGET' cannot be extracted" ;;
 esac
diff --git a/bin/gpgedit b/bin/gpgedit
--- a/bin/gpgedit
+++ b/bin/gpgedit
@@ -1,27 +1,23 @@
 #!/bin/bash
 
-if [ $# -ne 1 ]; then
-    exit 1
-fi
+[ $# -ne 1 ] && exit 1
 
-local file="$1"
-
-local extension="${file##*.}"
-local temp_file="$(mktemp).$extension"
+file="$1"
+extension="${file##*.}"
+temp_file="$(mktemp).$extension"
+[ ! -f "$file" ] && echo "Error: '$file' is not a valid file." && exit 1
 
 read -s -p "password: " password
 echo
 
 # decrypt
-if [ -f "$file" ]; then
-    gpg --batch --passphrase "$password" --decrypt "$file" > "$temp_file" 2>/dev/null \
-        || { echo -e "\033[31mdecryption failed, check password?\033[0m"; shred -uz "$temp_file"; exit 1; }
-fi
+gpg --batch --passphrase "$password" --decrypt "$file" > "$temp_file" 2>/dev/null \
+    || { echo -e "\033[31mdecryption failed, check password?\033[0m"; shred -uz "$temp_file"; exit 1; }
 
 # open temp in default editor
 ${EDITOR:-nvim} "$temp_file"
-
 shred -uz "$file"
+
 # encrypt the temp file and save it
 gpg --batch --symmetric --cipher-algo AES256 --passphrase "$password" --output "$file" "$temp_file" \
     && echo -e "file saved"
diff --git a/bin/i b/bin/i
--- a/bin/i
+++ b/bin/i
@@ -1,28 +1,25 @@
 #!/bin/env bash
 
-# Check the Linux distribution
-if [ -f /etc/os-release ]; then
-    . /etc/os-release
+[ ! -f /etc/os-release ] && echo "unable to determine the distro" && exit 1
+. /etc/os-release
 
-    case "$ID" in
-        arch)
-            if [ "$#" -eq 0 ]; then
-                pacman -Ssq | fzf-tmux -m -e --preview 'pacman -Si {}' --preview-window=right:55% | xargs -r sudo pacman -S --noconfirm
-                exit 0
-            fi
-            sudo pacman -S $@ || yay -S $@
-            ;;
-        debian|ubuntu|linuxmint|raspbian)
-            if [ "$#" -eq 0 ]; then
-                apt-cache pkgnames | fzf-tmux -h -m -e | xargs -r sudo apt install -y
-                exit 0
-            fi
-            sudo apt install -y "$@"
-            ;;
-        *)
-            echo "Unsupported distribution: $ID"
-            ;;
-    esac
-else
-    echo "/etc/os-release not found. Unable to determine the distribution."
-fi
+case "$ID" in
+    arch)
+        if [ "$#" -eq 0 ]; then
+            pacman -Ssq | fzf-tmux -m -e --preview 'pacman -Si {}' --preview-window=right:55% | xargs -r sudo pacman -S --noconfirm
+            exit 0
+        fi
+        sudo pacman -S $@ || yay -S $@
+        ;;
+    debian|ubuntu|linuxmint|raspbian)
+        if [ "$#" -eq 0 ]; then
+            apt-cache pkgnames | fzf-tmux -h -m -e | xargs -r sudo apt install -y
+            exit 0
+        fi
+        sudo apt install -y "$@"
+        ;;
+    *)
+        echo "unsupported distribution: $ID"
+        exit 1
+        ;;
+esac
diff --git a/bin/setbg b/bin/setbg
--- a/bin/setbg
+++ b/bin/setbg
@@ -29,25 +29,15 @@ else
     wall=$(nsxiv -otf ~/Pictures/Wallpapers)
 fi
 
-# Check if $wall is empty
-if [ -z "$wall" ]; then
-    random_wallpaper=$(ls ~/Pictures/Wallpapers/*.{jpg,png} | shuf -n 1)
-    wall="$random_wallpaper"
-fi
+[ -z "$wall" ] && wall=$(ls ~/Pictures/Wallpapers/*.{jpg,png} | shuf -n 1)
 
-if [ ! -f "$wall" ]; then
-    echo "Error: File '$wall' not found or not a valid file."
-    exit 1
-fi
+[ ! -f "$wall" ] && echo "Error: '$wall' not found" && exit 1
 
 # Set the wallpaper
 if [ -n "$WAYLAND_DISPLAY" ]; then
     killall swaybg
     nohup swaybg --mode "$mode" --image "$wall" > /tmp/output.log 2> /tmp/error.log &
 else
-    if [[ "$mode" == "fit" ]]; then
-        mode="max"
-    fi
+    [[ "$mode" == "fit" ]] && mode="max"
     feh --bg-$mode "$wall"
 fi
-
diff --git a/bin/t b/bin/t
--- a/bin/t
+++ b/bin/t
@@ -1,25 +1,22 @@
 #!/bin/env bash
 
-if [[ "$1" == "" ]]; then
-    exec "$0" "$PWD"
+[[ "$1" == "" ]] && exec "$0" "$PWD" && exit
+
+if tmux has-session -t "$@" 2>/dev/null; then
+    session_name="$@"
 else
-    if tmux has-session -t "$@" 2>/dev/null; then
-        session_name="$@"
-    else
-        target_dir=$(zoxide query "$@" 2>/dev/null)
+    target_dir=$(zoxide query "$@" 2>/dev/null)
 
-        if [[ -d "$target_dir" ]]; then
-            session_name="$(basename "$target_dir" | sed 's/\./_/g')"
-            tmux new -ds "$session_name" -c "$target_dir" 2>/dev/null
-        else
-            echo "error: no match found"
-            exit 1
-        fi
-    fi
-
-    if [[ "$TMUX" == "" ]]; then
-        tmux -u attach -t "$session_name"
+    if [[ -d "$target_dir" ]]; then
+        session_name="$(basename "$target_dir" | sed 's/\./_/g')"
+        tmux new -ds "$session_name" -c "$target_dir" 2>/dev/null
     else
-        tmux -u switch-client -t "$session_name"
+        echo "error: no match found" && exit 1
     fi
+fi
+
+if [[ "$TMUX" == "" ]]; then
+    tmux -u attach -t "$session_name"
+else
+    tmux -u switch-client -t "$session_name"
 fi
