rewrite

diff --git a/bin/i b/bin/i
--- a/bin/i
+++ b/bin/i
@@ -1,26 +1,19 @@
 #!/bin/env bash
 
-[ ! -f /etc/os-release ] && echo "unable to determine the distro" && exit 1
-. /etc/os-release
+menu() {
+    fzf-tmux -m -e --preview-window=right:55% --preview "$@" | xargs -r
+}
 
-case "$ID" in
-    arch)
-        if [ "$#" -eq 0 ]; then
-            pacman -Ssq \
-                | fzf-tmux -m -e --preview 'pacman -Si {}' --preview-window=right:55% \
-                | xargs -r sudo pacman -S --noconfirm
-            exit 0
-        fi
-        sudo pacman -S $@ || yay -S $@
-        ;;
-    debian|ubuntu|linuxmint|raspbian)
-        if [ "$#" -eq 0 ]; then
-            apt-cache pkgnames | fzf-tmux -h -m -e | xargs -r sudo apt install -y
-            exit 0
-        fi
-        sudo apt install -y "$@"
-        ;;
-    *)
-        echo "unsupported distribution: $ID" && exit 1
-        ;;
-esac
+if command -v apt &> /dev/null; then
+    [[ "$1" == "update" ]] && sudo apt update -y && exit
+    [[ "$#" != 0 ]] && sudo apt install $@ && exit
+    sudo apt install $(apt-cache pkgnames | menu "apt-cache show {}" || exit)
+
+elif command -v pacman &> /dev/null; then
+    [[ "$1" == "update" ]] && sudo pacman -Syu --noconfirm && exit
+    [[ "$#" != 0 ]] && sudo pacman -S $@ && exit
+    sudo pacman -S $(pacman -Ssq | menu "pacman -Si {}")
+
+else
+    echo "unsupported distribution: package manager not found" && exit 1
+fi
diff --git a/bin/remove b/bin/remove
--- a/bin/remove
+++ b/bin/remove
@@ -1,32 +1,27 @@
 #!/bin/env bash
 
-remove_arch() {
-    if [ "$#" -eq 0 ]; then
-        yay -Qq | fzf-tmux -h -m -e | xargs -r yay -R --noconfirm
-    elif [ "$1" == "all" ]; then
-        shift
-        sudo pacman -Rns "$@"
-    else
-        sudo pacman -R "$@"
-    fi
+menu() {
+    fzf-tmux -m -e --preview-window=right:55% --preview "$@" | xargs -r
 }
 
-remove_debian() {
+if command -v apt &> /dev/null; then
     if [ "$#" -eq 0 ]; then
-        apt list --installed | cut -d/ -f1 | fzf-tmux -h -m -e | xargs -r sudo apt remove -y
+        sudo apt remove $(apt list --installed | cut -d/ -f1 | menu 'apt-cache show {}')
     elif [ "$1" == "all" ]; then
         shift
-        sudo apt autoremove --purge -y "$@"
+        sudo apt autoremove --purge $@
     else
-        sudo apt remove -y "$@"
+        sudo apt remove $@
     fi
-}
-
-[ ! -f /etc/os-release ] && echo "unable to determine the distro" && exit
-. /etc/os-release
-
-case "$ID" in
-    arch) remove_arch "$@" ;;
-    debian|ubuntu|linuxmint|raspbian) remove_debian "$@" ;;
-    *) echo "unsupported distribution: $ID" ;;
-esac
+elif command -v pacman &> /dev/null; then
+    if [ "$#" -eq 0 ]; then
+        sudo pacman -R $(pacman -Qq | menu 'pacman -Qi {}')
+    elif [ "$1" == "all" ]; then
+        shift
+        sudo pacman -Rns $@
+    else
+        sudo pacman -R $@
+    fi
+else
+    echo "unsupported distribution: package manager not found" && exit 1
+fi
