cleanup

diff --git a/bin/i b/bin/i
--- a/bin/i
+++ b/bin/i
@@ -5,17 +5,24 @@ menu() {
 }
 
 if command -v apt &> /dev/null; then
-    [[ "$1" == "update" ]] && sudo apt update -y && exit
-    [[ "$#" != 0 ]] && sudo apt install $@ && exit
-    sel=$(apt-cache pkgnames | menu "apt-cache show {}")
-    [ -n "$sel" ] && sudo apt install $sel
-
+    if [[ "$1" == "update" ]]; then
+        sudo apt update -y
+    elif [[ "$#" != 0 ]]; then
+        sudo apt install $@
+    else
+        sel=$(apt-cache pkgnames | menu "apt-cache show {}")
+        [ -n "$sel" ] && sudo apt install $sel
+    fi
 elif command -v pacman &> /dev/null; then
-    [[ "$1" == "update" ]] && sudo pacman -Syu --noconfirm && exit
-    [[ "$#" != 0 ]] && sudo pacman -S $@ && exit
-    sel=$(pacman -Ssq | menu "pacman -Si {}")
-    [ -n "$sel" ] && sudo pacman -S $sel
-
+    if [[ "$1" == "update" ]]; then
+        sudo pacman -Syu --noconfirm
+    elif [[ "$#" != 0 ]]; then
+        sudo pacman -S $@
+    else
+        sel=$(pacman -Ssq | menu "pacman -Si {}")
+        [ -n "$sel" ] && sudo pacman -S $sel
+    fi
 else
-    echo "unsupported distribution: package manager not found" && exit 1
+    echo "unsupported distribution: package manager not found"
+    exit 1
 fi
diff --git a/bin/remove b/bin/remove
--- a/bin/remove
+++ b/bin/remove
@@ -5,25 +5,26 @@ menu() {
 }
 
 if command -v apt &> /dev/null; then
-    if [ "$#" -eq 0 ]; then
+    if [[ "$#" == 0 ]]; then
         sel=$(apt list --installed | cut -d/ -f1 | menu 'apt-cache show {}')
         [ -n "$sel" ] && sudo apt remove $sel
-    elif [ "$1" == "all" ]; then
+    elif [[ "$1" == "all" ]]; then
         shift
         sudo apt autoremove --purge $@
     else
         sudo apt remove $@
     fi
 elif command -v pacman &> /dev/null; then
-    if [ "$#" -eq 0 ]; then
+    if [[ "$#" == 0 ]]; then
         sel=$(pacman -Qq | menu 'pacman -Qi {}')
         [ -n "$sel" ] && sudo pacman -R $sel
-    elif [ "$1" == "all" ]; then
+    elif [[ "$1" == "all" ]]; then
         shift
         sudo pacman -Rns $@
     else
         sudo pacman -R $@
     fi
 else
-    echo "unsupported distribution: package manager not found" && exit 1
+    echo "unsupported distribution: package manager not found"
+    exit 1
 fi
