adds feature to take dirs

diff --git a/bin/setbg b/bin/setbg
--- a/bin/setbg
+++ b/bin/setbg
@@ -1,39 +1,29 @@
 #!/bin/env bash
 
-mode="fill"
-random=false
+wall="" mode="fill" random=false
 
-# Parse options
-while getopts "fctr" opt; do
+# parse options
+while getopts "fctrh" opt; do
     case $opt in
         f) mode="fit" ;;
         c) mode="center" ;;
         t) mode="tile" ;;
         r) random=true ;;
-        \?)
-            echo "Usage: $0 [-f fit] [-c center] [-t tile] [Image File] OR [-r random]"
-            exit 1
-            ;;
+        h|\?) echo -e "Usage: $0 \n\t[-f fit] [-c center] [-t tile] [image] \n\t[-r random] [-h help]" && exit 1 ;;
     esac
 done
 
-# Remove the parsed options from the positional parameters
+# remove parsed options
 shift $((OPTIND-1))
+wall_dir=${1:-"$HOME/Pictures/Wallpapers"}
 
-# Check if a wallpaper argument was passed
-if [ "$#" -eq 1 ]; then
-    wall="$1"
-elif "$random"; then
-    wall=""
-else
-    wall=$(nsxiv -otf ~/Pictures/Wallpapers)
-fi
+# some logical gymnastics
+[ -d "$wall_dir" ] && [[ "$random" == false ]] && wall=$(nsxiv -otf $wall_dir)
+[ -f "$wall_dir" ] && wall=$wall_dir
+[ -z "$wall" ] && wall=$(ls $wall_dir/*.{jpg,png} | shuf -n 1)
+[ ! -f "$wall" ] && echo "Error: wallpaper not found" && exit 1
 
-[ -z "$wall" ] && wall=$(ls ~/Pictures/Wallpapers/*.{jpg,png} | shuf -n 1)
-
-[ ! -f "$wall" ] && echo "Error: '$wall' not found" && exit 1
-
-# Set the wallpaper
+# set wallpaper
 if [ -n "$WAYLAND_DISPLAY" ]; then
     killall swaybg
     nohup swaybg --mode "$mode" --image "$wall" > /tmp/output.log 2> /tmp/error.log &
