t is now a fish script

diff --git a/bin/t b/bin/t
--- a/bin/t
+++ b/bin/t
@@ -1,27 +1,26 @@
-#!/bin/env bash
+#!/bin/env fish
+set this $(status -f)
 
-case "$1" in
-    ""|".")
-        [[ $PWD == $HOME ]] && tmux -u new -s "Main" && exit
-        exec $0 $PWD && exit
-        ;;
-    "menu")
-        sel=$(tmux ls -F '#S' 2>/dev/null \
-            | fzf-tmux +m -p 40%,30% +s --print-query --prompt='session: ' | tail -1)
-        [[ ! "$sel" ]] && exit
-        exec $0 $sel >/dev/null && exit
-        ;;
-esac
+switch "$argv[1]"
+	case "" "."
+        test $PWD = $HOME && tmux new -A -s "main" -n "notes" "nvim ~/notes/index" && exit
+		exec $this $PWD && exit
+	case "menu" "m"
+        set sel $(tmux ls -F '#S' 2>/dev/null \
+            | fzf-tmux +m -p 40%,30% +s --print-query --prompt='⚡ ' | tail -1)
+        test -z "$sel" && exit
+		exec $this $sel >/dev/null && exit
+end
 
-if tmux has -t "$@" 2>/dev/null; then
-    session="$@"
+if test $(tmux has -t "$argv" 2>/dev/null)
+    set session "$argv"
 else
-    [[ -d "$@" ]] && sj add "$@"
-    target_dir=$(sj query "$@" 2>/dev/null)
-    [[ ! -d "$target_dir" ]] && echo "error: no match found" && exit 1
+    test -d "$argv" && sj add "$argv"
+    set target_dir $(sj query "$argv" 2>/dev/null)
+    test ! -d "$target_dir" && echo "error: no match found" && exit 1
 
-    session="$(basename "$target_dir" | sed 's/\./_/g')"
+    set session "$(basename "$target_dir" | sed 's/\./_/g')"
     tmux new -ds "$session" -c "$target_dir" 2>/dev/null
-fi
+end
 
-[ -z "$TMUX" ] && tmux attach -t "$session" || tmux switch -t "$session"
+test -z "$TMUX" && tmux attach -t "$session" || tmux switch -t "$session"
